### ISSUE TITLE
Don't  hover html elements when resize the panel widgets

### ISSUE THREAD

**Issue by Max-ChenFei** [Max-ChenFei/Chaldene#138]
![Animation](https://user-images.githubusercontent.com/28513798/205508337-b5996d04-9e64-46de-8f52-6bc13de34985.gif)

**Comment by drcd1** [comment]
I cannot reproduce this one. Can you check if it still happens with the bigger padding between the divs?
If we do have to fix this, the only easy-ish fix I see is to hook a function triggered when this drag starts that places an invisible div over the whole window, so that mouse can never interact with anything else.
