### ISSUE TITLE
Move node draw function and different appearance status (selected, normal, hover) into node class from LGraphCanvas

### ISSUE THREAD

**Issue by Max-ChenFei** [Max-ChenFei/Chaldene#58]
The draw function should be one part of the node. The render only needs to call the function without knowing the detail.

**Comment by drcd1** [comment]
I strongly disagree with this, at least as is. Currently, our nodes have lots of information, not only about rendering, but also about interaction and other things. I suggest that his functionality should stay in the renderer, because otherwise, if we change rendering, we also have to change the nodes, and we don't have a clear layer of abstraction. However, we can have create a new object type in the renderer called "NodeRenderer" or something whose only purpose is to render nodes. This might encapsulate some behaviour. However, drawing nodes is so simple that I would suggest just using a function.

**Comment by Max-ChenFei** [comment]
The final solution after the discussion is we just keep the node class as a data description class.  When the node is added to the graph, the geometrical properties will be attached to the nodes. How to render this node is moved to one visual template class.

The visual template class defines how to draw different shapes of nodes and connectors.
